-- Seed minimal (extensibil) pentru "Contul de execuție - Cheltuieli"
-- Include titluri/subtotaluri + o parte din subcoduri uzuale (10.xx si 20.xx).
-- Idempotent: ON DUPLICATE KEY UPDATE.

INSERT INTO budget_indicators
  (indicator_type, capitol, subcapitol, paragraf, indicator_code, name, ca_cb, row_kind, calc_expression, indent_level, display_order, is_active)
VALUES
  -- TOTAL / Subtotaluri mari
  ('EXPENSE', NULL, NULL, NULL, 'TOTAL', 'TOTAL CHELTUIELI (01+70+79)', NULL, 'TITLE', '01+70+79', 0, 10, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '01', 'CHELTUIELI CURENTE (10+20+30+40+50+51+55+57+59)', NULL, 'GROUP', '10+20+30+40+50+51+55+57+59', 1, 20, TRUE),

  -- TITLUL I
  ('EXPENSE', NULL, NULL, NULL, '10', 'TITLUL I CHELTUIELI DE PERSONAL (cod 10.01+10.02+10.03)', NULL, 'GROUP', '10.01+10.02+10.03', 1, 30, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01', 'Cheltuieli salariale in bani (cod 10.01.01 la 10.01.30)', NULL, 'GROUP', NULL, 2, 40, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.01', 'Salarii de baza', NULL, 'LEAF', NULL, 3, 41, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.02', 'Salarii de merit', NULL, 'LEAF', NULL, 3, 42, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.03', 'Indemnizatie de conducere', NULL, 'LEAF', NULL, 3, 43, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.04', 'Spor de vechime', NULL, 'LEAF', NULL, 3, 44, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.05', 'Sporuri pentru conditii de munca', NULL, 'LEAF', NULL, 3, 45, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.06', 'Alte sporuri', NULL, 'LEAF', NULL, 3, 46, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.07', 'Ore suplimentare', NULL, 'LEAF', NULL, 3, 47, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.08', 'Fond de premii', NULL, 'LEAF', NULL, 3, 48, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.09', 'Prima de vacanta', NULL, 'LEAF', NULL, 3, 49, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.10', 'Fond pentru posturi ocupate prin cumul', NULL, 'LEAF', NULL, 3, 50, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.11', 'Fond aferent platii cu ora', NULL, 'LEAF', NULL, 3, 51, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.12', 'Indemnizatii platite unor persoane din afara unitatii', NULL, 'LEAF', NULL, 3, 52, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.13', 'Indemnizatii de delegare', NULL, 'LEAF', NULL, 3, 53, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.14', 'Indemnizatii de detasare', NULL, 'LEAF', NULL, 3, 54, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.15', 'Alocatii pentru transportul la si de la locul de munca', NULL, 'LEAF', NULL, 3, 55, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.16', 'Alocatii pentru locuinte', NULL, 'LEAF', NULL, 3, 56, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.01.30', 'Alte drepturi salariale in bani', NULL, 'LEAF', NULL, 3, 57, TRUE),

  ('EXPENSE', NULL, NULL, NULL, '10.02', 'Cheltuieli salariale in natura (cod 10.02.01 la 10.02.30)', NULL, 'GROUP', NULL, 2, 120, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.02.01', 'Tichete de masa', NULL, 'LEAF', NULL, 3, 121, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.02.02', 'Norme de hrana', NULL, 'LEAF', NULL, 3, 122, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.02.03', 'Uniforme si echipament obligatoriu', NULL, 'LEAF', NULL, 3, 123, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.02.04', 'Locuinta de serviciu folosita de salariat si familia sa', NULL, 'LEAF', NULL, 3, 124, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.02.05', 'Transportul la si de la locul de munca', NULL, 'LEAF', NULL, 3, 125, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.02.30', 'Alte drepturi salariale in natura', NULL, 'LEAF', NULL, 3, 126, TRUE),

  ('EXPENSE', NULL, NULL, NULL, '10.03', 'Contributii (cod 10.03.01 la 10.03.06)', NULL, 'GROUP', NULL, 2, 160, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.03.01', 'Contributii de asigurari sociale de stat', NULL, 'LEAF', NULL, 3, 161, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.03.02', 'Contributii de asigurari de somaj', NULL, 'LEAF', NULL, 3, 162, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.03.03', 'Contributii de asigurari sociale de sanatate', NULL, 'LEAF', NULL, 3, 163, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.03.04', 'Contributii de asigurari pentru accidente de munca si boli profesionale', NULL, 'LEAF', NULL, 3, 164, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.03.05', 'Prime de asigurare viata platite de angajator pentru angajati', NULL, 'LEAF', NULL, 3, 165, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '10.03.06', 'Contributii pentru concedii si indemnizatii', NULL, 'LEAF', NULL, 3, 166, TRUE),

  -- TITLUL II
  ('EXPENSE', NULL, NULL, NULL, '20', 'TITLUL II BUNURI SI SERVICII (cod 20.01 la 20.30)', NULL, 'GROUP', NULL, 1, 400, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01', 'Bunuri si servicii (cod 20.01.01 la 20.01.30)', NULL, 'GROUP', NULL, 2, 410, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.01', 'Furnituri de birou', NULL, 'LEAF', NULL, 3, 411, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.02', 'Materiale pentru curatenie', NULL, 'LEAF', NULL, 3, 412, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.03', 'Incalzit, iluminat si forta motrica', NULL, 'LEAF', NULL, 3, 413, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.04', 'Apa, canal si salubritate', NULL, 'LEAF', NULL, 3, 414, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.05', 'Carburanti si lubrifianti', NULL, 'LEAF', NULL, 3, 415, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.06', 'Piese de schimb', NULL, 'LEAF', NULL, 3, 416, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.07', 'Transport', NULL, 'LEAF', NULL, 3, 417, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.08', 'Posta, telecomunicatii, radio, tv, internet', NULL, 'LEAF', NULL, 3, 418, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.09', 'Materiale si prestari de servicii cu caracter functional', NULL, 'LEAF', NULL, 3, 419, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.01.30', 'Alte bunuri si servicii pentru intretinere si functionare', NULL, 'LEAF', NULL, 3, 420, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.02', 'Reparatii curente', NULL, 'GROUP', NULL, 2, 430, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.03', 'Hrana (cod 20.03.01+20.03.02)', NULL, 'GROUP', '20.03.01+20.03.02', 2, 440, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.03.01', 'Hrana pentru oameni', NULL, 'LEAF', NULL, 3, 441, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.03.02', 'Hrana pentru animale', NULL, 'LEAF', NULL, 3, 442, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.04', 'Medicamente si materiale sanitare (cod 20.04.01 la 20.04.04)', NULL, 'GROUP', NULL, 2, 450, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.04.01', 'Medicamente', NULL, 'LEAF', NULL, 3, 451, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.04.02', 'Materiale sanitare', NULL, 'LEAF', NULL, 3, 452, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.04.03', 'Reactivi', NULL, 'LEAF', NULL, 3, 453, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.04.04', 'Dezinfectanti', NULL, 'LEAF', NULL, 3, 454, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.05', 'Bunuri de natura obiectelor de inventar (cod 20.05.01 la 20.05.30)', NULL, 'GROUP', NULL, 2, 460, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.05.01', 'Uniforme si echipament', NULL, 'LEAF', NULL, 3, 461, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.05.03', 'Lenjerie si accesorii de pat', NULL, 'LEAF', NULL, 3, 462, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.05.30', 'Alte obiecte de inventar', NULL, 'LEAF', NULL, 3, 463, TRUE),

  -- Continuare TITLUL II (20.06+ ...)
  ('EXPENSE', NULL, NULL, NULL, '20.06', 'Deplasari, detasari, transferari (cod 20.06.01+20.06.02)', NULL, 'GROUP', '20.06.01+20.06.02', 2, 470, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.06.01', 'Deplasari interne, detasari, transferari', NULL, 'LEAF', NULL, 3, 471, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.06.02', 'Deplasari in strainatate', NULL, 'LEAF', NULL, 3, 472, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.09', 'Materiale de laborator', NULL, 'LEAF', NULL, 2, 480, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.10', 'Cercetare-dezvoltare', NULL, 'LEAF', NULL, 2, 490, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.11', 'Carti, publicatii si materiale documentare', NULL, 'LEAF', NULL, 2, 500, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.12', 'Consultanta si expertiza', NULL, 'LEAF', NULL, 2, 510, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.13', 'Pregatire profesionala', NULL, 'LEAF', NULL, 2, 520, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.14', 'Protectia muncii', NULL, 'LEAF', NULL, 2, 530, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.15', 'Munitie, furnituri si armament de natura activelor fixe pentru armata', NULL, 'LEAF', NULL, 2, 540, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.16', 'Studii si cercetari', NULL, 'LEAF', NULL, 2, 550, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.18', 'Plati pentru finantarea patrimoniului genetic al animalelor', NULL, 'LEAF', NULL, 2, 560, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.20', 'Reabilitare infrastructura program inundatii pentru autoritati publice locale', NULL, 'LEAF', NULL, 2, 570, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.21', 'Meteorologie', NULL, 'LEAF', NULL, 2, 580, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.22', 'Finantarea actiunilor din domeniul apelor', NULL, 'LEAF', NULL, 2, 590, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.23', 'Prevenirea si combaterea inundatiilor si ingheturilor', NULL, 'LEAF', NULL, 2, 600, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.24', 'Comisioane si alte costuri aferente imprumuturilor (cod 20.24.01 la 20.24.03)', NULL, 'GROUP', NULL, 2, 610, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.24.01', 'Comisioane si alte costuri aferente imprumuturilor externe', NULL, 'LEAF', NULL, 3, 611, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.24.02', 'Comisioane si alte costuri aferente imprumuturilor interne', NULL, 'LEAF', NULL, 3, 612, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.24.03', 'Stabilirea riscului de tara', NULL, 'LEAF', NULL, 3, 613, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30', 'Alte cheltuieli (cod 20.30.01 la 20.30.30)', NULL, 'GROUP', NULL, 2, 700, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.01', 'Reclama si publicitate', NULL, 'LEAF', NULL, 3, 701, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.02', 'Protocol si reprezentare', NULL, 'LEAF', NULL, 3, 702, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.03', 'Prime de asigurare non-viata', NULL, 'LEAF', NULL, 3, 703, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.04', 'Chirii', NULL, 'LEAF', NULL, 3, 704, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.06', 'Prestari servicii pentru transmiterea drepturilor', NULL, 'LEAF', NULL, 3, 705, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.07', 'Fondul Presedintelui/Fondul conducatorului institutiei publice', NULL, 'LEAF', NULL, 3, 706, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.08', 'Fondul Primului ministru', NULL, 'LEAF', NULL, 3, 707, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.09', 'Executarea silita a creantelor bugetare', NULL, 'LEAF', NULL, 3, 708, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '20.30.30', 'Alte cheltuieli cu bunuri si servicii', NULL, 'LEAF', NULL, 3, 709, TRUE),

  -- TITLUL III DOBANZI
  ('EXPENSE', NULL, NULL, NULL, '30', 'TITLUL III DOBANZI (cod 30.01+30.02+30.03)', NULL, 'GROUP', '30.01+30.02+30.03', 1, 1200, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.01', 'Dobanzi aferente datoriei publice interne (cod 30.01.01+30.01.02)', NULL, 'GROUP', '30.01.01+30.01.02', 2, 1210, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.01.01', 'Dobanzi aferente datoriei publice interne directe', NULL, 'LEAF', NULL, 3, 1211, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.01.02', 'Dobanzi aferente creditelor interne garantate', NULL, 'LEAF', NULL, 3, 1212, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.02', 'Dobanzi aferente datoriei publice externe (cod 30.02.01 la 30.02.05)', NULL, 'GROUP', NULL, 2, 1220, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.02.01', 'Dobanzi aferente datoriei publice externe directe', NULL, 'LEAF', NULL, 3, 1221, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.02.02', 'Dobanzi aferente creditelor externe contractate de ordonatorii de credite', NULL, 'LEAF', NULL, 3, 1222, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.02.03', 'Dobanzi aferente creditelor externe garantate si/sau directe subimprumutate', NULL, 'LEAF', NULL, 3, 1223, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.02.05', 'Dobanzi aferente datoriei publice externe locale', NULL, 'LEAF', NULL, 3, 1225, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.03', 'Alte dobanzi (cod 30.03.01 la 30.03.05)', NULL, 'GROUP', NULL, 2, 1230, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.03.01', 'Dobanzi aferente imprumuturilor din fondul de tezaur', NULL, 'LEAF', NULL, 3, 1231, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.03.02', 'Dobanda datorata trezoreriei statului', NULL, 'LEAF', NULL, 3, 1232, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.03.03', 'Dobanzi aferente imprumuturilor temporare din trezoreria statului', NULL, 'LEAF', NULL, 3, 1233, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.03.04', 'Dobanzi la depozite si disponibilitati pastrate in contul trezoreriei statului', NULL, 'LEAF', NULL, 3, 1234, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '30.03.05', 'Dobanzi la operatiunile de leasing', NULL, 'LEAF', NULL, 3, 1235, TRUE),

  -- TITLUL IV SUBVENTII
  ('EXPENSE', NULL, NULL, NULL, '40', 'TITLUL IV SUBVENTII (cod 40.01 la 40.30)', NULL, 'GROUP', NULL, 1, 1400, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.01', 'Subventii pe produse', NULL, 'LEAF', NULL, 2, 1401, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.02', 'Subventii pe activitati', NULL, 'LEAF', NULL, 2, 1402, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.03', 'Subventii pentru acoperirea diferentelor de pret si tarif', NULL, 'LEAF', NULL, 2, 1403, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.04', 'Subventii pentru sustinerea transportului feroviar public de calatori', NULL, 'LEAF', NULL, 2, 1404, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.05', 'Subventii pentru transportul de calatori cu metroul', NULL, 'LEAF', NULL, 2, 1405, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.06', 'Actiuni de ecologizare', NULL, 'LEAF', NULL, 2, 1406, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.07', 'Valorificarea cenusilor de pirita', NULL, 'LEAF', NULL, 2, 1407, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.08', 'Subventii pentru dobanzi la credite bancare', NULL, 'LEAF', NULL, 2, 1408, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.09', 'Plati catre angajatori pentru formarea profesionala a angajatilor', NULL, 'LEAF', NULL, 2, 1409, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.10', 'Fonduri nerambursabile pentru crearea de noi locuri de munca', NULL, 'LEAF', NULL, 2, 1410, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.11', 'Prime acordate producatorilor agricoli', NULL, 'LEAF', NULL, 2, 1411, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.12', 'Subventii pentru completarea primelor de asigurare pentru factorii de risc din agricultura', NULL, 'LEAF', NULL, 2, 1412, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.13', 'Stimularea exporturilor', NULL, 'LEAF', NULL, 2, 1413, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.14', 'Sustinerea infrastructurii de transport', NULL, 'LEAF', NULL, 2, 1414, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.15', 'Sprijinirea producatorilor agricoli', NULL, 'LEAF', NULL, 2, 1415, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.16', 'Programe de conservare sau de inchidere a minelor', NULL, 'LEAF', NULL, 2, 1416, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.17', 'Programe de protectie sociala si integrare socioprofesionala a persoanelor cu handicap', NULL, 'LEAF', NULL, 2, 1417, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.18', 'Protectie sociala in sectorul minier', NULL, 'LEAF', NULL, 2, 1418, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.19', 'Plati pentru stimularea crearii de locuri de munca', NULL, 'LEAF', NULL, 2, 1419, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '40.30', 'Alte subventii', NULL, 'LEAF', NULL, 2, 1430, TRUE),

  -- TITLUL V FONDURI DE REZERVA
  ('EXPENSE', NULL, NULL, NULL, '50', 'TITLUL V FONDURI DE REZERVA (cod 50.01 la 50.04)', NULL, 'GROUP', NULL, 1, 1500, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '50.01', 'Fond de rezerva bugetara la dispozitia Guvernului', NULL, 'LEAF', NULL, 2, 1501, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '50.02', 'Fond de interventie la dispozitia Guvernului', NULL, 'LEAF', NULL, 2, 1502, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '50.04', 'Fond de rezerva bugetara la dispozitia autoritatilor locale', NULL, 'LEAF', NULL, 2, 1504, TRUE),

  -- TITLUL VI TRANSFERURI
  ('EXPENSE', NULL, NULL, NULL, '51', 'TITLUL VI TRANSFERURI INTRE UNITATI ALE ADMINISTRATIEI PUBLICE (cod 51.01+51.02)', NULL, 'GROUP', '51.01+51.02', 1, 1600, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01', 'Transferuri curente (cod 51.01.01 la 51.01.26)', NULL, 'GROUP', NULL, 2, 1610, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.01', 'Transferuri catre institutii publice', NULL, 'LEAF', NULL, 3, 1611, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.02', 'Finantarea de baza a invatamantului superior', NULL, 'LEAF', NULL, 3, 1612, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.03', 'Actiuni de sanatate', NULL, 'LEAF', NULL, 3, 1613, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.04', 'Finantarea drepturilor acordate persoanelor cu handicap', NULL, 'LEAF', NULL, 3, 1614, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.05', 'Finantarea aeroporturilor de interes local', NULL, 'LEAF', NULL, 3, 1615, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.06', 'Transferuri din Fondul de interventie', NULL, 'LEAF', NULL, 3, 1616, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.07', 'Transferuri din bugetul de stat catre bugetul asigurarilor sociale de stat', NULL, 'LEAF', NULL, 3, 1617, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.08', 'Transferuri din bugetul de stat catre bugetul asigurarilor pentru somaj', NULL, 'LEAF', NULL, 3, 1618, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.09', 'Transferuri privind contributii de sanatate pentru persoane care satisfac serviciul militar in termen', NULL, 'LEAF', NULL, 3, 1619, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.10', 'Transferuri privind contributii de sanatate pentru persoane care executa pedepse private de libertate sau arest preventiv', NULL, 'LEAF', NULL, 3, 1620, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.11', 'Transferuri din bugetul de stat catre bugetul fondului national unic de asigurari sociale de sanatate', NULL, 'LEAF', NULL, 3, 1621, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.12', 'Contributia persoanelor asigurate pentru finantarea ocrotirii sanatatii', NULL, 'LEAF', NULL, 3, 1622, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.13', 'Transferuri pentru lucrarile de cadastru imobiliar', NULL, 'LEAF', NULL, 3, 1623, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.14', 'Transferuri din bugetele consiliilor judetene pentru finantarea centrelor de zi pentru protectia copilului', NULL, 'LEAF', NULL, 3, 1624, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.15', 'Transferuri din bugetele locale pentru institutiile de asistenta sociala pentru persoanele cu handicap', NULL, 'LEAF', NULL, 3, 1625, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.16', 'Transferuri din bugetul asigurarilor sociale de stat catre bugetul fondului national unic de asigurari sociale de sanatate', NULL, 'LEAF', NULL, 3, 1626, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.17', 'Transferuri din bugetul asigurarilor pentru somaj catre bugetul asigurarilor sociale de stat', NULL, 'LEAF', NULL, 3, 1627, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.18', 'Transferuri din bugetul asigurarilor pentru somaj catre bugetele locale pentru finantarea programelor pentru ocuparea temporara a fortei de munca', NULL, 'LEAF', NULL, 3, 1628, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.19', 'Transferuri din bugetul asigurarilor pentru somaj catre bugetul fondului national unic de asigurari sociale de sanatate', NULL, 'LEAF', NULL, 3, 1629, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.20', 'Transferuri din bugetul asigurarilor pentru somaj catre bugetul asigurarilor sociale de stat reprezentand asigurare pentru accidente de munca si boli profesionale pentru someri pe durata practicii profesionale', NULL, 'LEAF', NULL, 3, 1630, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.21', 'Transferuri din bugetul asigurarilor sociale de stat catre bugetul fondului national unic de asigurari sociale de sanatate pentru persoane aflate in concediu medical din cauza de accident de munca sau boala profesionala', NULL, 'LEAF', NULL, 3, 1631, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.22', 'Transferuri reprezentand cota-parte din tarifele de utilizare a spectrului', NULL, 'LEAF', NULL, 3, 1632, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.23', 'Varsaminte catre bugetul FNUASS din valorificarea creantelor bugetare', NULL, 'LEAF', NULL, 3, 1633, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.24', 'Transferuri din bugetele consiliilor locale si judetene pentru acordarea unor ajutoare in situatii de extrema dificultate', NULL, 'LEAF', NULL, 3, 1634, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.25', 'Programe pentru sanatate', NULL, 'LEAF', NULL, 3, 1635, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.01.26', 'Transferuri privind contributia de asigurari sociale de sanatate pentru persoane aflate in concediu pentru cresterea copilului', NULL, 'LEAF', NULL, 3, 1636, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02', 'Transferuri de capital (cod 51.02.01 la 51.02.11)', NULL, 'GROUP', NULL, 2, 1650, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.01', 'Finantarea strazilor care se vor amenaja in perimetrele destinate constructiilor de cvartale de locuinte noi', NULL, 'LEAF', NULL, 3, 1651, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.02', 'Finantarea investitiilor finantate partial din imprumuturi externe', NULL, 'LEAF', NULL, 3, 1652, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.03', 'Programul pentru pietruirea drumurilor si alimentarea cu apa a satelor', NULL, 'LEAF', NULL, 3, 1653, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.04', 'Programul pentru constructii de locuinte si sali de sport', NULL, 'LEAF', NULL, 3, 1654, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.05', 'Finantarea elaborarii si/sau actualizarii planurilor urbanistice generale si a regulamentelor locale de urbanism', NULL, 'LEAF', NULL, 3, 1655, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.06', 'Retehnologizarea centralelor termice si electrice de termoficare', NULL, 'LEAF', NULL, 3, 1656, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.07', 'Finantarea studiilor de fezabilitate aferente proiectelor SAPARD', NULL, 'LEAF', NULL, 3, 1657, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.08', 'Aparatura medicala si echipamente de comunicatii in urgenta', NULL, 'LEAF', NULL, 3, 1658, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.09', 'Finantarea actiunilor privind reducerea riscului seismic al constructiilor existente cu destinatie de locuinta', NULL, 'LEAF', NULL, 3, 1659, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.10', 'Plati din contul creditelor garantate si/sau subimprumutate', NULL, 'LEAF', NULL, 3, 1660, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '51.02.11', 'Transferuri pentru reparatii capitale la spitale', NULL, 'LEAF', NULL, 3, 1661, TRUE),

  -- TITLUL VII / VIII / IX (liste scurte, restul se poate completa cu +Adaugă rând dacă e nevoie)
  ('EXPENSE', NULL, NULL, NULL, '55', 'TITLUL VII ALTE TRANSFERURI (cod 55.01+55.02+55.03)', NULL, 'GROUP', '55.01+55.02+55.03', 1, 1700, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '55.01', 'Transferuri interne (cod 55.01.01 la 55.01.18)', NULL, 'GROUP', NULL, 2, 1710, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '55.02', 'Transferuri curente in strainatate (cod 55.02.01 la 55.02.04)', NULL, 'GROUP', NULL, 2, 1720, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '55.03', 'Contributia Romaniei la bugetul U.E. (cod 55.03.01 la 55.03.10)', NULL, 'GROUP', NULL, 2, 1730, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '57', 'TITLUL VIII ASISTENTA SOCIALA (cod 57.01+57.02)', NULL, 'GROUP', '57.01+57.02', 1, 1800, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '57.01', 'Asigurari sociale', NULL, 'LEAF', NULL, 2, 1801, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '57.02', 'Ajutoare sociale (cod 57.02.01+57.02.02)', NULL, 'GROUP', '57.02.01+57.02.02', 2, 1802, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '57.02.01', 'Ajutoare sociale in numerar', NULL, 'LEAF', NULL, 3, 1803, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '57.02.02', 'Ajutoare sociale in natura', NULL, 'LEAF', NULL, 3, 1804, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '59', 'TITLUL IX ALTE CHELTUIELI (cod 59.01 la 59.24)', NULL, 'GROUP', NULL, 1, 1900, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '59.01', 'Burse', NULL, 'LEAF', NULL, 2, 1901, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '59.02', 'Ajutoare pentru daune provocate de calamitatile naturale', NULL, 'LEAF', NULL, 2, 1902, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '59.03', 'Finantarea partidelor politice', NULL, 'LEAF', NULL, 2, 1903, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '59.24', 'Finantarea ansamblului \"Memorialul revolutiei - Decembrie 1989\" din municipiul Timisoara', NULL, 'LEAF', NULL, 2, 1924, TRUE),

  -- CHELTUIELI DE CAPITAL (70) + subcoduri 71/72
  ('EXPENSE', NULL, NULL, NULL, '71', 'TITLUL X ACTIVE NEFINANCIARE (cod 71.01+71.02)', NULL, 'GROUP', '71.01+71.02', 2, 8100, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '71.01', 'Active fixe (cod 71.01.01 la 71.01.30)', NULL, 'GROUP', NULL, 3, 8110, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '71.01.01', 'Constructii', NULL, 'LEAF', NULL, 4, 8111, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '71.01.02', 'Masini, echipamente si mijloace de transport', NULL, 'LEAF', NULL, 4, 8112, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '71.01.03', 'Mobilier, aparatura birotica si alte active corporale', NULL, 'LEAF', NULL, 4, 8113, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '71.01.30', 'Alte active fixe (inclusiv reparatii capitale)', NULL, 'LEAF', NULL, 4, 8130, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '71.02', 'Stocuri (cod 71.02.01)', NULL, 'GROUP', NULL, 3, 8140, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '71.02.01', 'Rezerve de stat si de mobilizare', NULL, 'LEAF', NULL, 4, 8141, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '72', 'TITLUL XI ACTIVE FINANCIARE (cod 72.01)', NULL, 'GROUP', '72.01', 2, 8200, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '72.01', 'Participare la capitalul social al societatilor comerciale', NULL, 'LEAF', NULL, 3, 8201, TRUE),

  -- OPERATIUNI FINANCIARE (79) + subcoduri 80/81
  ('EXPENSE', NULL, NULL, NULL, '80', 'TITLUL XII IMPRUMUTURI (cod 80.01 la 80.30)', NULL, 'GROUP', NULL, 2, 9100, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '80.01', 'Imprumuturi acordate pentru obiective aprobate prin conventii bilaterale si interguvernamentale', NULL, 'LEAF', NULL, 3, 9101, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '80.02', 'Imprumuturi pentru persoane cu statut de refugiat', NULL, 'LEAF', NULL, 3, 9102, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '80.30', 'Alte imprumuturi', NULL, 'LEAF', NULL, 3, 9130, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81', 'TITLUL XIII RAMBURSARI DE CREDITE (cod 81.01+81.02)', NULL, 'GROUP', '81.01+81.02', 2, 9200, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.01', 'Rambursari de credite externe (cod 81.01.01 la 81.01.06)', NULL, 'GROUP', NULL, 3, 9210, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.01.01', 'Rambursari de credite externe contractate de ordonatorii de credite', NULL, 'LEAF', NULL, 4, 9211, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.01.02', 'Rambursari de credite externe garantate si directe subimprumutate', NULL, 'LEAF', NULL, 4, 9212, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.01.05', 'Rambursari de credite aferente datoriei publice externe locale', NULL, 'LEAF', NULL, 4, 9215, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.01.06', 'Diferente de curs aferente datoriei publice externe', NULL, 'LEAF', NULL, 4, 9216, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.02', 'Rambursari de credite interne (cod 81.02.01 la 81.02.05)', NULL, 'GROUP', NULL, 3, 9220, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.02.01', 'Rambursari de credite interne garantate', NULL, 'LEAF', NULL, 4, 9221, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.02.02', 'Diferente de curs aferente datoriei publice interne', NULL, 'LEAF', NULL, 4, 9222, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '81.02.05', 'Rambursari de credite aferente datoriei publice interne locale', NULL, 'LEAF', NULL, 4, 9225, TRUE),

  -- TITLUL XIV
  ('EXPENSE', NULL, NULL, NULL, '90', 'TITLUL XIV REZERVE, EXCEDENT/DEFICIT', NULL, 'GROUP', '91.01+92.01+93.01', 1, 9900, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '91.01', 'Rezerve', NULL, 'LEAF', NULL, 2, 9901, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '92.01', 'Excedent', NULL, 'LEAF', NULL, 2, 9902, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '93.01', 'Deficit', NULL, 'LEAF', NULL, 2, 9903, TRUE),

  -- Agregari mari pentru TOTAL
  ('EXPENSE', NULL, NULL, NULL, '70', 'CHELTUIELI DE CAPITAL (cod 71+72)', NULL, 'GROUP', '71+72', 1, 8000, TRUE),
  ('EXPENSE', NULL, NULL, NULL, '79', 'OPERATIUNI FINANCIARE (cod 80+81)', NULL, 'GROUP', '80+81', 1, 9000, TRUE)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  ca_cb = VALUES(ca_cb),
  row_kind = VALUES(row_kind),
  calc_expression = VALUES(calc_expression),
  indent_level = VALUES(indent_level),
  display_order = VALUES(display_order),
  is_active = TRUE,
  updated_at = CURRENT_TIMESTAMP;


